### ISSUE TITLE
SSH logins cause a new X session

### ISSUE THREAD

**Issue by tranquilitycal** [flamewave000/concerto_rpi#2]
I had noticed this prior to forking and had fixed it in my version but with all the modifications I made I figured it not in the best interest to just submit a pull request. 

Whenever you go to manage the Raspberry Pi via SSH the moment you log in as say the pi user it causes a new Xorg server to be started in front of the already running session which also causes the display to stop working.

A solution to fix this is removing the autologin portion in the "InstallConcertoForPi.sh" script. That code tells the system that the moment a new bash session is started to run "startx" and cause the new session to run. I find this code unnecessary as you can already have the Raspberry Pi to login automatically through raspi-config.

As I said some of the modifications I made might be worth looking at and maybe taking a few into the master. I thank you for the wonderful script.

**Comment by flamewave000** [comment]
It's great to see that you've had some good use of the scripts I set up. I know I didn't have the issue you mention way back when I first wrote the scripts, so I'm assuming it's something that started happening in later versions of the Raspbian OS. I actually haven't used Concerto since I finished University (where we were using it around the campus). I will make the change you suggest.
